### ISSUE TITLE
Quick repeated clicks on the 'X' generates a warning

### ISSUE THREAD

**Issue by asafratzon** [ealush/butter-toast#109]
Clicking more than once (rapidly) on the 'X' of a notification pop-up results in the following React warning:

![image](https://user-images.githubusercontent.com/2094413/54051876-ded41000-41b0-11e9-88c0-feee18d8339e.png)

After I first saw this warning it took me sometime to understand how to reproduce it because I mistakenly did it (clicked 'X' twice rapidly).

Please confirm that this is not only on my environment.
If so, I think the fix is trivial and I'll be glad to assist with a PR but will need some guidance on the process as this will be my first time.

Cheers.

**Comment by ealush** [comment]
Hrm. Hadn't noticed it myself, but I can understand where this could be coming from.

I'd very much like you to assist solving this one, and I can see multiple solutions to it.
The easiest would be probably making a change to the Toast specific `dismiss` function: https://github.com/ealush/butter-toast/blob/master/src/Toast/index.js#L94 . Maybe adding a closure that holds the clicked-state. We could just as well use an actual state change, but I don't know if triggering re-render is worth it when trying to unmount a toast.

Hit me with a PR, or just ask anything. I'd be glad to help out :)

Thanks!

**Comment by asafratzon** [comment]
Sure, I'm on it 👍

**Comment by asafratzon** [comment]
Hey again.

I've cloned the repo and wanted to build it and first see that I can use the local build.
I installed all dependencies, ran 'npm run-script build', and tried to change my import lines from my project from:
`import ButterToast, { Cinnamon, POS_TOP, POS_CENTER } from "butter-toast";`
to:
`import ButterToast, { Cinnamon, POS_TOP, POS_CENTER } from "../../../../butter-toast/dist/butter-toast";`

But then I see in the browser:
`Uncaught Error: Cannot find module '../../../../butter-toast/dist/butter-toast'`

I assume it's something basic that I'm missing here.
Any assistance will be much appreciated.
Cheers.

**Comment by benbenedek** [comment]
Hey @asafratzon ,

I am not sure changing your imports is the way to go about testing your changes locally.

I would look into reading about `npm link`

Here's a quick link to get you started: https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557

Hope this helps.

**Comment by asafratzon** [comment]
Thanks @benbenedek ! will take a look.

**Comment by asafratzon** [comment]
Fixed in #113 , closing.
