### ISSUE TITLE
How to change width?

### ISSUE THREAD

**Issue by hatton** [ealush/butter-toast#135]
The toast is cutting off lines:
![image](https://user-images.githubusercontent.com/8448/70570333-eb7aff80-1b58-11ea-816b-2087d69bc247.png)
It looks like the element I want to change the width on has only generated classes:

![image](https://user-images.githubusercontent.com/8448/70570387-064d7400-1b59-11ea-9f46-6134b264a93d.png)

And setting the `className` only effects a much higher level parent.

Ideas?

**Comment by ealush** [comment]
Hey @hatton, thanks for reaching out. 

Yeah, this won't be great. I don't intend on changing the structure throughout this major, but as you mentioned, it is prone to break.

I think I'll solve it with the following changes:

1. Add a static class name for all toasts.
2. Allow you to set a class name for your toasts, globally through your tray, or individually through the emit function. 

I can work on these two over the weekend, I'll update this issue when I publish the new version.

**Comment by hatton** [comment]
Cool, thanks.

**Comment by ealush** [comment]
Hey, sorry for taking a bit longer. You can now install butter-toast@3.3.5 which adds a distinct classname for each of the cinnamon templates.

`toast-crisp`, `toast-crunch` and `toast-slim`. You can directly select these now.
![image](https://user-images.githubusercontent.com/11255103/70988475-972cce00-20ca-11ea-856b-8d436b383330.png)
![image](https://user-images.githubusercontent.com/11255103/70988552-bfb4c800-20ca-11ea-9d9a-d7afef4273a9.png)
