### ISSUE TITLE
Use babel-plugin-transform-runtime 

### ISSUE THREAD

**Issue by kern** [ealush/butter-toast#24]
Thanks for this project! :)

Currently butter-toast includes babel-polyfill, which will pollute the global scope and cannot be loaded concurrently with another babel-polyfill. Libraries are suggested to use babel-plugin-transform-runtime: https://babeljs.io/docs/plugins/transform-runtime/

**Comment by ealush** [comment]
Hey @kern, thanks for reaching out 👍 
I've published 1.0.1. Looks like I was using both transform-runtime and babel polyfill. It seems to solve it on my end.

Can you please confirm that the problem is solved on your end as well?

**Comment by kern** [comment]
LGTM! Thanks @ealush. :)
