### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by netanelben** [ealush/butter-toast#37]
When rendering ButterToast on the server, using Express.js + ReactDOMServer, getting `ReferenceError: window is not defined`

Suggested solution: use the global object.

**Comment by ealush** [comment]
Good point. When writing Butter-Toast I did not think of server side rendered applications.

Using the `global` object would not help much here, as we are using `window` as an EventTarget. Calling `global.dispatchEvent()` would throw an error, the same for `addEventListener`.

Also, if we could simply solve it by using `global`, we would face other DOM related errors. For example, when creating a new instance of butter toast, we do:

```js
document.createElement('aside');
root.setAttribute('class', className);
document.body.appendChild(root);
```

This isn't going to work on a server rendered app, nor should it, as it creates elements outside of the  app itself, which is great for client side rendering - but useless for server side rendering.

I would suggest the following:

__Client side rendering__
Operate normally, everything should work.

__Server side rendering__
* if `renderInContext` is set to `true`: render the elements using react (as it works now), without attaching any event listener.
* if `renderInContext` is set to `false` (or is undefined): do nothing.

# What can we do until it gets fixed?
It should be simple enough to require ButterToast only in your client-side-rendered entry point, and initialize it only there.

**Comment by ealush** [comment]
being taken care of by @netanelben in https://github.com/ealush/butter-toast/pull/57

**Comment by ealush** [comment]
Done 👍
