### ISSUE TITLE
[FEATURE] Add global `dismiss` method

### ISSUE THREAD

**Issue by ealush** [ealush/butter-toast#64]
## Feature description
Add a `ButterToast.dismiss()` method that dismisses visible toasts according to different matching criteria

### Tray name matching
Dismisses all toasts from a specific tray (with a given name);

```js
ButterToast.dismiss({
    name: 'tray-name'
});
```

### Toast Id matching
```js
ButterToast.dismiss({
    toastId: 'toastId'
});
```

### All toast dismissal
Dismisses all active toasts.
```js
ButterToast.dismiss();
```

**Comment by Pymossy** [comment]
Hi,

I did this here [Fork](https://github.com/Pymossy/butter-toast).
Do you have any comment?

Best
