### ISSUE TITLE
butter-toast breaking the styles of page

### ISSUE THREAD

**Issue by cihati** [ealush/butter-toast#89]
This is about to drive me crazy:

I would like to use butter-toast (have 3.0.4), I managed to make it work (i.e. I do see a nice toast). BUT, it removes the other styles which come through styled-components.

Things I've tried:
1) Making sure my app and butter-toast have the same styled-components version (and that no other stuff in my node_modules use styled-components, i.e. 3.4.9)
2) Did the webpack tricks in https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page (even though I already don't get the following error, so this shouldn't be an issue for me anyways)

> It looks like there are several instances of "styled-components" initialized in this application.
> This may cause dynamic styles not rendering properly, errors happening during rehydration process
> and makes you application bigger without a good reason.
> 
> If you are using a building tool like Webpack, consider checking your bundle for duplication
> of "styled-components" module.

After spending many hours and reading many styled-components help pages, I still can't make it work. I have webpack 4.16.0 fwiw.

before clicking:
![image](https://user-images.githubusercontent.com/461998/45898778-e6565700-bdd2-11e8-8c33-414325c6b88a.png)

after clicking:
![image](https://user-images.githubusercontent.com/461998/45898751-d63e7780-bdd2-11e8-8e99-ef1038214ab3.png)

any ideas @ealush ?

many thanks!

**Comment by ealush** [comment]
Hey @cihati, thank you for reporting this issue, and I am sorry that you are experiencing this issue. This indeed seems like an issue with styled-components not being smart about multiple instances.

I am trying to figure out a fix. I published an `rc` version in which both styled-components and polished are marked as externals. Can you please try using it and see if it works for you?

`npm install --save butter-toast@3.1.0-rc.2`

and to use it:
```js
import ButterToast, { Cinnamon, POS_BOTTOM, POS_RIGHT } from 'butter-toast/dist/noconflict.min.js';
```

You will need to have both `styled-components` and `polished` installed for it to work. See [here](https://stackblitz.com/edit/react-tnwkru?file=index.js).

Can you please let me know if that worked for you? If it does, I will publish a new version with the fix.
