### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by kenshinman** [ealush/butter-toast#90]
Getting this Error

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/butter-toast/dist/butter-toast.min.js:1:362

Read more here: http://bit.ly/2tRViJ9

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c react-scripts build
Directory: /Users/...
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kenshinman/Desktop/softcom/learn_org/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How can I resolve this

**Comment by kenshinman** [comment]
@ealush thanks for the response, but had to look for an alternative because of the urgency of the project.

@dominikgyecsek no I didn't resolve it but would have loved to use it because it's like the most beautiful toast i've seen in a while

**Comment by ealush** [comment]
@kenshinman, I know it has been a long time since you closed this issue, but in case you are still interested: the issue seems to have been resolved with the latest major of react-scripts. See here: https://github.com/ealush/butter-toast/issues/104
